color: null
description: null
fieldLayouts:
  f6477be7-f75d-44f4-812e-86335c7e05e2:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-10-27T11:02:09+00:00'
            disabled: false
            elementCondition: null
            id: null
            includeInCards: false
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            providesThumbs: false
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: e497661d-ecbe-4fd7-9330-cf5418309ce1
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-27T12:59:22+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: ecc8b910-8de2-4dff-9f56-b8c2fb1a5ea1 # Tekst 
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: e15ebd63-c25f-4bfa-96e7-99d48fbc7ef6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2025-10-31T11:17:30+00:00'
            editCondition: null
            elementCondition: null
            fieldUid: d419b9ec-3b83-48e2-a5d5-7d675cd35d06 # Afbeelding
            handle: null
            includeInCards: false
            instructions: null
            label: null
            providesThumbs: false
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a3650864-cf77-402e-8997-dbf6c7ef16f8
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: b80a966a-cb62-4fb8-8ea3-52ff4c408076
        userCondition: null
handle: blog
hasTitleField: true
icon: folder
name: Blog
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
