allowLineBreaksInTitles: true
color: yellow
description: null
fieldLayouts:
  98d5fbac-c974-453b-a671-0876324433ed:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2025-10-08T11:55:41+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 880b0bcc-6186-4b71-b7e6-39d3afe13757 # Weergave
            handle: null
            instructions: null
            label: null
            required: true
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 40504c54-5098-4510-8181-77bf5ff0668b
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-03-09T11:03:36+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: 880b0bcc-6186-4b71-b7e6-39d3afe13757 # Weergave
                  layoutElementUid: 40504c54-5098-4510-8181-77bf5ff0668b
                  operator: in
                  uid: e4b1f09e-2808-42b9-9e59-72715ea3aa16
                  values:
                    - blogs
              elementType: craft\elements\Entry
              fieldContext: global
            elementEditCondition: null
            fieldUid: af908524-48f4-4030-b6b5-619ff14bacdc # Boolean
            handle: showSome
            instructions: null
            label: 'Toon enkele'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a52ef843-aae8-4bc3-b158-d896eab745ca
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-03-09T13:59:52+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: af908524-48f4-4030-b6b5-619ff14bacdc # Boolean
            handle: noTitleText
            instructions: null
            label: 'Geen titel en tekst'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: a7f0a83f-d5c4-4f6a-a056-f1bd527cb293
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-03-10T08:32:55+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: 880b0bcc-6186-4b71-b7e6-39d3afe13757 # Weergave
                  layoutElementUid: 40504c54-5098-4510-8181-77bf5ff0668b
                  operator: in
                  uid: eb5eb330-46ed-4082-8757-258dfca03f47
                  values:
                    - solutions
                    - industries
              elementType: craft\elements\Entry
              fieldContext: global
            elementEditCondition: null
            fieldUid: af908524-48f4-4030-b6b5-619ff14bacdc # Boolean
            handle: asAccordion
            instructions: null
            label: 'Als Accordion'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 5d16e535-c17c-4013-b29b-e6ec859b2d02
            userCondition: null
            warning: null
            width: 50
          -
            dateAdded: '2026-03-10T15:49:29+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\elements\conditions\entries\SectionConditionRule
                  operator: in
                  uid: 0b79f4d6-f7c7-439e-97f9-2ed8dec097ef
                  values:
                    - 925e875f-2662-48af-af0b-9828ecbfbabb # Solutions
                    - 921c0d73-9e49-4b11-aeda-59d9a7d23434 # Industries
              elementType: craft\elements\Entry
              fieldContext: global
            elementEditCondition: null
            fieldUid: af908524-48f4-4030-b6b5-619ff14bacdc # Boolean
            handle: showChildren
            instructions: null
            label: 'Toon enkel nakomelingen'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: dd4a4046-0bb0-43ee-b9ce-4ecb9124c8bd
            userCondition: null
            warning: null
            width: 50
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2025-10-08T11:54:23+00:00'
            disabled: false
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: af908524-48f4-4030-b6b5-619ff14bacdc # Boolean
                  layoutElementUid: a7f0a83f-d5c4-4f6a-a056-f1bd527cb293
                  uid: 07bce445-920d-4bf2-8f01-fc56d6ef6553
                  value: false
              elementType: craft\elements\Entry
              fieldContext: global
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 958d8d47-8dde-4b15-a172-ec76d37fa15c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-03-09T11:04:02+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\LightswitchFieldConditionRule
                  fieldUid: af908524-48f4-4030-b6b5-619ff14bacdc # Boolean
                  layoutElementUid: a7f0a83f-d5c4-4f6a-a056-f1bd527cb293
                  uid: b7373d3a-8478-4c23-a39f-554a1084e878
                  value: false
              elementType: craft\elements\Entry
              fieldContext: global
            elementEditCondition: null
            fieldUid: 58a18928-e4be-4f0f-8851-7a1fc536130a # Tekst
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fdd82c1a-0566-41e9-bb36-b7f48b6c124c
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-03-09T14:20:35+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: b26636b7-849b-4fb5-b0af-ecdfd309b7c4 # Tekst
            handle: linkTitle
            instructions: null
            label: 'Titel bij link'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d8ce3f3e-ca2f-49e9-9afd-c0f0a0e5f150
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-03-09T11:04:02+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: bb7becdd-3a77-49f6-bf93-f1fd1d9d8f9a # Link
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 7a9d1e18-7282-4cf8-84bc-683154d244ca
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 59533a5b-03f6-4a92-af14-40de6695f53a
        userCondition: null
    thumbFieldKey: null
handle: contentDisplay
hasTitleField: true
icon: folder-grid
name: 'Content overzicht'
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: '{ title ? title : display.value }'
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{ title }'
