allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  b505f83d-0c58-42d3-8df9-3232254e10dc:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-03-06T10:52:47+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 3670dc78-77b4-4fc4-965c-76668ba6cd60
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: cccba4a8-a24c-43f3-ac40-f63af6f2fca6
        userCondition: null
    thumbFieldKey: null
handle: industries
hasTitleField: true
icon: null
name: Industries
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
