allowLineBreaksInTitles: true
color: yellow
description: null
fieldLayouts:
  9bef1916-25c2-413c-8864-fc86080df4b2:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-03-09T13:18:34+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 8f0db651-05cb-4d73-9531-29f24587491d # Lijst type
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: b28436f2-3bfa-4892-9297-2d30fb77615c
            userCondition: null
            warning: null
            width: 100
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-03-06T11:29:19+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 79582a3d-164e-4c23-a4a3-6aec6390c9c4
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-03-10T15:26:08+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: 7bf8a881-40d9-405e-8ff9-01327db24e82 # Tekst
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: d6da1685-06f7-4540-9ac3-b20e9d4cd56a
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-03-10T12:03:08+00:00'
            editCondition: null
            elementCondition: null
            elementEditCondition: null
            fieldUid: bb7becdd-3a77-49f6-bf93-f1fd1d9d8f9a # Link
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0f4b0646-6439-4366-9b26-b9ae9bc2e48e
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-03-09T13:18:34+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: 8f0db651-05cb-4d73-9531-29f24587491d # Lijst type
                  layoutElementUid: b28436f2-3bfa-4892-9297-2d30fb77615c
                  operator: in
                  uid: 149e7705-944e-459b-8262-d83c6fcf9a8e
                  values:
                    - faq
              elementType: craft\elements\Entry
              fieldContext: global
            elementEditCondition: null
            fieldUid: 91a218c7-298e-4670-8058-d50adfc09650 # Lijst titel en tekst
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: ce3855ee-4dc4-404f-895b-93c72930ef94
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-03-09T13:21:09+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: 8f0db651-05cb-4d73-9531-29f24587491d # Lijst type
                  layoutElementUid: b28436f2-3bfa-4892-9297-2d30fb77615c
                  operator: in
                  uid: 6ed18c16-3d77-47c3-b773-0661f69962d7
                  values:
                    - icons
              elementType: craft\elements\Entry
              fieldContext: global
            elementEditCondition: null
            fieldUid: 9db5369a-8f2a-4874-b761-38504550498b # Lijst titel, tekst en icoon
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: fd7d263c-c7d8-47d3-ae34-5d09d3f466a6
            userCondition: null
            warning: null
            width: 100
          -
            dateAdded: '2026-03-10T15:25:38+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: 8f0db651-05cb-4d73-9531-29f24587491d # Lijst type
                  layoutElementUid: b28436f2-3bfa-4892-9297-2d30fb77615c
                  operator: in
                  uid: 4a480126-eebc-4c85-9003-b41363c71fff
                  values:
                    - checks
              elementType: craft\elements\Entry
              fieldContext: global
            elementEditCondition: null
            fieldUid: 43a90934-c974-41c1-9585-fb96d742bec9 # Tekst Lijst
            handle: null
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0545c778-2813-4984-bc80-45ebd7a0bf9a
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 1a7c9a4f-fb69-4b82-a5fa-6477b2f7d9e6
        userCondition: null
      -
        elementCondition: null
        elements:
          -
            dateAdded: '2026-03-11T10:15:53+00:00'
            editCondition: null
            elementCondition:
              class: craft\elements\conditions\entries\EntryCondition
              conditionRules:
                -
                  class: craft\fields\conditions\OptionsFieldConditionRule
                  fieldUid: 8f0db651-05cb-4d73-9531-29f24587491d # Lijst type
                  layoutElementUid: b28436f2-3bfa-4892-9297-2d30fb77615c
                  operator: in
                  uid: 5086f56e-5d2f-4114-bae5-4e32c2574bd7
                  values:
                    - icons
              elementType: craft\elements\Entry
              fieldContext: global
            elementEditCondition: null
            fieldUid: 1a9192ca-f304-4288-bef7-3d8252065024 # Boolean On
            handle: withBg
            instructions: null
            label: 'Met achtergrond'
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 6813195d-ed8a-4ac6-abcd-3706bee1bcfe
            userCondition: null
            warning: null
            width: 100
        name: Instellingen
        uid: f254138c-28c6-43ce-bd3b-f4be31ecccd0
        userCondition: null
    thumbFieldKey: null
handle: list
hasTitleField: true
icon: list
name: Lijst
showSlugField: false
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
