allowLineBreaksInTitles: false
color: null
description: null
fieldLayouts:
  0adca20f-ca19-48d4-a973-4e53d3985f0a:
    cardThumbAlignment: end
    tabs:
      -
        elementCondition: null
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            dateAdded: '2026-03-06T12:15:50+00:00'
            disabled: false
            elementCondition: null
            id: null
            inputType: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            required: true
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 9b534495-a43c-4891-af45-3f1220cac301
            userCondition: null
            warning: null
            width: 100
        name: Content
        uid: 29e30812-5bab-4c3b-9197-9804ebdc44a2
        userCondition: null
    thumbFieldKey: null
handle: titleOnly
hasTitleField: true
icon: null
name: Title
showSlugField: true
showStatusField: true
slugTranslationKeyFormat: null
slugTranslationMethod: site
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
uiLabelFormat: '{title}'
