headingLevels:
  - 2
  - 3
  - 4
  - 5
  - 6
name: Expanded
toolbar:
  - heading
  - '|'
  - bold
  - italic
  - underline
  - numberedList
  - bulletedList
  - link
  - subscript
  - superscript
  - insertImage
  - mediaEmbed
  - sourceEditing
