columnSuffix: null
handle: ckeExpanded
instructions: null
name: 'Tekst '
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  characterLimit: null
  css: null
  defaultTransform: null
  fullGraphqlData: true
  headingLevels:
    - 2
    - 3
    - 4
    - 5
    - 6
  js: null
  options: null
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  toolbar:
    - heading
    - '|'
    - bold
    - italic
    - underline
    - numberedList
    - bulletedList
    - link
    - subscript
    - superscript
    - insertImage
    - mediaEmbed
    - sourceEditing
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
