columnSuffix: null
handle: ckeSimple
instructions: null
name: Tekst
searchable: false
settings:
  availableTransforms: ''
  availableVolumes: '*'
  characterLimit: null
  css: null
  defaultTransform: null
  fullGraphqlData: true
  headingLevels: false
  js: null
  options: null
  parseEmbeds: false
  purifierConfig: null
  purifyHtml: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  showWordCount: false
  sourceEditingGroups:
    - __ADMINS__
  toolbar:
    - heading
    - '|'
    - bold
    - underline
    - italic
    - link
  wordLimit: null
translationKeyFormat: null
translationMethod: none
type: craft\ckeditor\Field
