columnSuffix: null
handle: display
instructions: null
name: Weergave
searchable: false
settings:
  customOptions: false
  iconsOnly: false
  options:
    -
      __assoc__:
        -
          - label
          - 'News & updates'
        -
          - value
          - blogs
        -
          - icon
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Solutions
        -
          - value
          - solutions
        -
          - icon
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Industries
        -
          - value
          - industries
        -
          - icon
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Locaties
        -
          - value
          - locations
        -
          - icon
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\ButtonGroup
