columnSuffix: null
handle: file
instructions: null
name: Bestand
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - excel
    - pdf
    - powerpoint
    - word
  branchLimit: null
  defaultPlacement: end
  defaultUploadLocationSource: 'volume:a11a6090-1726-4b54-8d4c-452b8a10527b' # Bestanden
  defaultUploadLocationSubpath: '{ rootOwner.section ?? owner.owner.section ?? entry.section  }'
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: true
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:a11a6090-1726-4b54-8d4c-452b8a10527b' # Bestanden
  restrictedLocationSubpath: '{ rootOwner.section ?? owner.owner.section ?? entry.section  }'
  selectionLabel: null
  showCardsInGrid: false
  showSearchInput: true
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:a11a6090-1726-4b54-8d4c-452b8a10527b' # Bestanden
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
