columnSuffix: null
handle: graphic
instructions: null
name: Grafisch
searchable: false
settings:
  allowSelfRelations: false
  allowSubfolders: false
  allowUploads: true
  allowedKinds:
    - image
  branchLimit: null
  defaultPlacement: end
  defaultUploadLocationSource: 'volume:f78d7b04-49b9-42bc-a2d9-0fa1bcac226c' # Grafisch
  defaultUploadLocationSubpath: '{ rootOwner.section ?? owner.owner.section ?? entry.section  }'
  maintainHierarchy: false
  maxRelations: 1
  minRelations: null
  previewMode: full
  restrictFiles: true
  restrictLocation: false
  restrictedDefaultUploadSubpath: null
  restrictedLocationSource: 'volume:f78d7b04-49b9-42bc-a2d9-0fa1bcac226c' # Grafisch
  restrictedLocationSubpath: '{ rootOwner.section ?? owner.owner.section ?? entry.section  }'
  selectionLabel: null
  showSearchInput: true
  showSiteMenu: true
  showUnpermittedFiles: false
  showUnpermittedVolumes: false
  sources:
    - 'volume:f78d7b04-49b9-42bc-a2d9-0fa1bcac226c' # Grafisch
  targetSiteId: null
  validateRelatedElements: false
  viewMode: list
translationKeyFormat: null
translationMethod: none
type: craft\fields\Assets
