columnSuffix: null
handle: listType
instructions: null
name: 'Lijst type'
searchable: false
settings:
  customOptions: false
  iconsOnly: false
  options:
    -
      __assoc__:
        -
          - label
          - Faq
        -
          - value
          - faq
        -
          - icon
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Icons
        -
          - value
          - icons
        -
          - icon
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Checks
        -
          - value
          - checks
        -
          - icon
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Accordion
        -
          - value
          - accordion
        -
          - icon
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Grid
        -
          - value
          - grid
        -
          - icon
          - ''
        -
          - default
          - ''
    -
      __assoc__:
        -
          - label
          - Certificaten
        -
          - value
          - certificates
        -
          - icon
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\ButtonGroup
