columnSuffix: null
handle: typeSlider
instructions: null
name: 'Slider type'
searchable: false
settings:
  customOptions: false
  iconsOnly: false
  options:
    -
      __assoc__:
        -
          - label
          - Brands
        -
          - value
          - brands
        -
          - icon
          - ''
        -
          - default
          - '1'
    -
      __assoc__:
        -
          - label
          - Timeline
        -
          - value
          - timeline
        -
          - icon
          - ''
        -
          - default
          - ''
translationKeyFormat: null
translationMethod: none
type: craft\fields\ButtonGroup
