defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: e7d4a70c-a925-4f2d-a4d5-403db94ee1cd # Vaste content
handle: blogFixedContent
maxAuthors: 1
name: 'Vaste content blog'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  19c6391b-a582-4651-b999-d4761e7a122c: # vydraulics
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: single
