defaultPlacement: end
enableVersioning: true
entryTypes:
  -
    uid: 809abac6-c0fa-4e26-ace3-b78963f017f1 # Herbuikbare Blok
handle: reusableBlocks
maxAuthors: 1
name: 'Herbruikbare blokken'
previewTargets:
  -
    label: 'Primary entry page'
    refresh: '1'
    urlFormat: '{url}'
propagationMethod: all
siteSettings:
  19c6391b-a582-4651-b999-d4761e7a122c: # Vydraulics EN
    enabledByDefault: true
    hasUrls: false
    template: null
    uriFormat: null
type: channel
